---

verbose: true

# The URL of the InfluxDB server.
influxdb_url: "http://localhost:8086"

# The address and port this proxy should bind to.
bind:
  address: 0.0.0.0
  port:    3004

# Per-database mappings from GROUP BY time $interval to retention
# policies.
#
# Top level entries are InfluxDB database names with corresponding
# mappings.  The _default_ entry will be used for queries with a
# database not explicitly named.
#
# Second-level entries are be the fixed set of GROUP BY time $interval
# values used by Grafana with corresponding InfluxDB retention policy
# names to which inbound queries should be mapped.
#
# All 15 possible $interval values used by Grafana should be present
# in a given mapping.
rps_by_interval:
  # Example below replicates the default behavior of Grafana.
  _default_:
    0.1s: default
    1s:   default
    5s:   default
    10s:  default
    30s:  default
    1m:   default
    5m:   default
    10m:  default
    30m:  default
    1h:   default
    3h:   default
    12h:  default
    1d:   default
    7d:   default
    30d:  default
  # Example below is more complete:
  # 
  # _default_:
  #   0.1s: default
  #   1s:   default
  #   5s:   default
  #   10s:  10sec
  #   30s:  30sec
  #   1m:   1min
  #   5m:   5min
  #   10m:  30min
  #   30m:  30min
  #   1h:   1hour
  #   3h:   3hour
  #   12h:  12hour
  #   1d:   24hour
  #   7d:   24hour
  #   30d:  24hour
